CREATE DATABASE PROJECT

USE PROJECT

CREATE TABLE USER_REGSTER(
SERIAL			BIGINT IDENTITY(1,1) PRIMARY KEY,
UID				NVARCHAR(MAX),
PROFILE_FOR		NVARCHAR(MAX),
NAME			NVARCHAR(MAX),
RELIGION		NVARCHAR(MAX),
MOBILE			NVARCHAR(MAX),
EMAIL			NVARCHAR(MAX),
PASS			NVARCHAR(MAX))

SELECT NAME FROM USER_REGSTER WHERE UID=ani@gmail.com

SELECT * FROM USER_REGSTER



INSERT INTO USER_REGSTER VALUES('201973','SELF','PALAK','HINDU','89374793870','PALAK@GMAIL.COM','000')

CREATE TABLE USER_PROFILE(
SERIAL			BIGINT IDENTITY(1,1) PRIMARY KEY,
UID				NVARCHAR(MAX),
IMGPATH			NVARCHAR(MAX),
GENDER			NVARCHAR(MAX),
NAME			NVARCHAR(MAX),
DOB				DATETIME,
AGE				NVARCHAR(MAX),
BIRTH_TIME		NVARCHAR(MAX),
BIRTH_CITY		NVARCHAR(MAX),
CASTE			NVARCHAR(MAX),
RELIGION		NVARCHAR(MAX),
MOTHER_TOGNUE	NVARCHAR(MAX),
BODYTYPE		NVARCHAR(MAX),
HEIGHT			NVARCHAR(MAX),
WEIGHT			NVARCHAR(MAX),
COMPLEXTION		NVARCHAR(MAX),
BLOODGROUP		NVARCHAR(MAX),
MARITIAL_STATUS	NVARCHAR(MAX),
ZODIAC_SIGN		NVARCHAR(MAX),
EDUCATION		NVARCHAR(MAX),
PROFESSION		NVARCHAR(MAX),
ANNUAL_INCOME	NVARCHAR(MAX),
JOB_LOCATION	NVARCHAR(MAX),
FATHER_NAME		NVARCHAR(MAX),
FATHER_OCCU		NVARCHAR(MAX),
MOTHER_NAME		NVARCHAR(MAX),
MOTHER_OCCU		NVARCHAR(MAX),
ADDRESS			NVARCHAR(MAX),
CITY			NVARCHAR(MAX),
STATE			NVARCHAR(MAX),
CONTACT			NVARCHAR(MAX),
FAMILY_TYPE		NVARCHAR(MAX),
NO_SISTER		NVARCHAR(MAX),
NO_BROTHER		NVARCHAR(MAX),
STATUS			NVARCHAR(MAX))


SELECT * FROM USER_PROFILE where uid='16957002901715184920193943'
 
select * from USER_REGSTER where uid='16957002901715184920193943'
update USER_PROFILE set gender= 'Female' where serial =4
SELECT IMGPATH, NAME, AGE, ANNUAL_INCOME FROM USER_PROFILE WHERE AGE BETWEEN 21 AND 25

CREATE  PROC UPDATE_PROFILE
@UID				NVARCHAR(MAX),
@IMGPATH			NVARCHAR(MAX),
@GENDER				NVARCHAR(MAX),
@NEAM				NVARCHAR(MAX),
@DOB				DATETIME,
@AGE				NVARCHAR(MAX),
@BIRTH_TIME			NVARCHAR(MAX),
@BIRTH_CITY			NVARCHAR(MAX),
@CASTE				NVARCHAR(MAX),
@RELIGION			NVARCHAR(MAX),
@MOTHER_TOGNUE		NVARCHAR(MAX),
@BODYTYPE			NVARCHAR(MAX),
@HEIGHT				NVARCHAR(MAX),
@WEIGHT				NVARCHAR(MAX),
@COMPLEXTION		NVARCHAR(MAX),
@BLOODGROUP			NVARCHAR(MAX),
@MARITIAL_STATUS	NVARCHAR(MAX),
@ZODIAC_SIGN		NVARCHAR(MAX),
@EDUCATION			NVARCHAR(MAX),
@PROFESSION			NVARCHAR(MAX),
@ANNUAL_INCOME		NVARCHAR(MAX),
@JOB_LOCATION		NVARCHAR(MAX),
@FATHER_NAME		NVARCHAR(MAX),
@FATHER_OCCU		NVARCHAR(MAX),
@MOTHER_NAME		NVARCHAR(MAX),
@MOTHER_OCCU		NVARCHAR(MAX),
@ADDRESS			NVARCHAR(MAX),
@CITY				NVARCHAR(MAX),
@STATE				NVARCHAR(MAX),
@CONTACT			NVARCHAR(MAX),
@FAMILY_TYPE		NVARCHAR(MAX),
@NO_SISTER			NVARCHAR(MAX),
@NO_BROTHER 		NVARCHAR(MAX),
@STATUS				NVARCHAR(MAX)
AS BEGIN
UPDATE USER_PROFILE SET IMGPATH=@IMGPATH, GENDER=@GENDER, NAME=@NEAM, DOB=@DOB, AGE=@AGE, BIRTH_TIME=@BIRTH_TIME, BIRTH_CITY=@BIRTH_CITY, CASTE=@CASTE, RELIGION=@RELIGION, MOTHER_TOGNUE=@MOTHER_TOGNUE, BODYTYPE=@BODYTYPE, HEIGHT=@HEIGHT, WEIGHT=@WEIGHT, COMPLEXTION=@COMPLEXTION, BLOODGROUP=@BLOODGROUP, MARITIAL_STATUS=@MARITIAL_STATUS, ZODIAC_SIGN=@ZODIAC_SIGN, EDUCATION=@EDUCATION, PROFESSION=@PROFESSION, ANNUAL_INCOME=@ANNUAL_INCOME, JOB_LOCATION=@JOB_LOCATION, FATHER_NAME=@FATHER_NAME, FATHER_OCCU=@FATHER_OCCU, MOTHER_NAME=@MOTHER_NAME, MOTHER_OCCU=@MOTHER_OCCU, ADDRESS=@ADDRESS, CITY=@CITY, STATE=@STATE, CONTACT=@CONTACT, FAMILY_TYPE=@FAMILY_TYPE, NO_SISTER=@NO_SISTER, NO_BROTHER=@NO_BROTHER, STATUS='Actived'  WHERE UID=@UID
END

DROP PROC UPDATE_PROFILE


INSERT INTO USER_PROFILE VALUES('201973','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','PENDING')

CREATE TABLE USER_EXPECTION(
SERIAL					BIGINT IDENTITY(1,1) PRIMARY KEY,
UID						NVARCHAR(MAX),
MARITIAL_STATUS			NVARCHAR(MAX),
INCOME					NVARCHAR(MAX),
BODYTYPE				NVARCHAR(MAX),
COMPLEXTION				NVARCHAR(MAX),
EDUCATION				NVARCHAR(MAX),
FMAILY_TYPE				NVARCHAR(MAX),
STATUS					NVARCHAR(MAX))	
SELECT *FROM USER_PROFILE

CREATE PROC UPDATE_EXPECTION(
@UID						NVARCHAR(MAX),
@MARITIAL_STATUS			NVARCHAR(MAX),
@INCOME						NVARCHAR(MAX),
@BODYTYPE					NVARCHAR(MAX),
@COMPLEXTION				NVARCHAR(MAX),
@EDUCATION					NVARCHAR(MAX),
@FMAILY_TYPE				NVARCHAR(MAX),
@STATUS						NVARCHAR(MAX))	
AS BEGIN
UPDATE USER_EXPECTION SET MARITIAL_STATUS=@MARITIAL_STATUS, INCOME=@INCOME, BODYTYPE=@BODYTYPE, COMPLEXTION=@COMPLEXTION, EDUCATION=@EDUCATION, FMAILY_TYPE=@FMAILY_TYPE, STATUS='ACTIVED' WHERE UID=@UID
END

DROP PROC Update_EXPECTION


INSERT INTO USER_EXPECTION VALUES('','','','','','','PENDING')

TRUNCATE TABLE USER_REGSTER
TRUNCATE TABLE USER_PROFILE
TRUNCATE TABLE USER_EXPECTION
TRUNCATE TABLE CONTACT

ALTER TABLE USER_PROFILE ALTER COLUMN AGE INT

ALTER TABLE USER_PROFILE ALTER COLUMN STATUS NVARCHAR(MAX)

SELECT * FROM USER_EXPECTION

ALTER TABLE USER_PROFILE ADD DEFAULT 'PENDING' FOR STATUS


CREATE TABLE CONTACT(
SERIAL      BIGINT IDENTITY(1,1) PRIMARY KEY,
NAME		NVARCHAR(MAX),
EMAIL		NVARCHAR(MAX),
TEXT		NVARCHAR(MAX))

DROP TABLE CONTACT

SELECT * FROM CONTACT

INSERT INTO CONTACT VALUES('PALAK','PALAK@GMAIL.COM','AWESOME SITE')